import type { Metadata } from "next";
import "./globals.css";
import {Image, MantineProvider} from "@mantine/core";
import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import {NavBar} from "@/navigation/Navbar";
import {Footer} from "@/navigation/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <NavBar />
          <Image src="/banner.jpeg" alt="logo" h={200} />
            <main>{children}</main>
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
